CREATE TABLE Shotgun (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  img TEXT NOT NULL,
  gauge TEXT NOT NULL,
  shot TEXT NOT NULL,
  powder TEXT NOT NULL,
  primer TEXT NOT null,
  shell TEXT NOT null,
  price INTEGER NOT null,
  fps INTEGER NOT null,
  min INTEGER NOT null,
  avg INTEGER NOT null,
  max INTEGER NOT null,
  paragraph TEXT NOT NULL
);