CREATE TABLE Pistol (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  img TEXT NOT NULL,
  caliber TEXT NOT NULL,
  bullet TEXT NOT NULL,
  powder TEXT NOT NULL,
  primer TEXT NOT null,
  brandcase TEXT NOT null,
  price INTEGER NOT null,
  fps INTEGER NOT null,
  min INTEGER NOT null,
  avg INTEGER NOT null,
  max INTEGER NOT null,
  paragraph TEXT NOT NULL
);